BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Produk" (
	"KD_BRG"	INTEGER,
	"NM_BRG"	TEXT,
	"HRG_BRG"	INTEGER,
	"STK_BRG"	INTEGER
);
INSERT INTO "Produk" VALUES (1,'Mesin 2JZ',200,20);
INSERT INTO "Produk" VALUES (2,'Mesin RB26',250,10);
COMMIT;
